### ISSUE TITLE
Handle email messages with duplicate Mime-Version headers

### ISSUE THREAD

**Issue by lafiosca** [lafiosca/reba#1]
Messages from backerkit.com, sent via Mailgun, were rejected for having duplicate Mime-Version headers when we relayed them through SES. Example event:

```
{
    "Records": [
        {
            "eventSource": "aws:ses",
            "eventVersion": "1.0",
            "ses": {
                "mail": {
                    "timestamp": "2020-03-26T22:39:58.712Z",
                    "source": "bounce+bd464f.74ae96-joe=example.com@s.backerkit.com",
                    "messageId": "7agm2c84tgclj4ejvdvrjol7dq7s4l4v0ev2o4g1",
                    "destination": [
                        "joe@example.com"
                    ],
                    "headersTruncated": false,
                    "headers": [
                        {
                            "name": "Return-Path",
                            "value": "<bounce+bd464f.74ae96-joe=example.com@s.backerkit.com>"
                        },
                        {
                            "name": "Received",
                            "value": "from mail-m86.mailgun.info (mail-m86.mailgun.info [146.20.113.86]) by inbound-smtp.us-east-1.amazonaws.com with SMTP id 7agm2c84tgclj4ejvdvrjol7dq7s4l4v0ev2o4g1 for joe@example.com; Thu, 26 Mar 2020 22:39:58 +0000 (UTC)"
                        },
                        {
                            "name": "X-SES-Spam-Verdict",
                            "value": "PASS"
                        },
                        {
                            "name": "X-SES-Virus-Verdict",
                            "value": "PASS"
                        },
                        {
                            "name": "Received-SPF",
                            "value": "pass (spfCheck: domain of s.backerkit.com designates 146.20.113.86 as permitted sender) client-ip=146.20.113.86; envelope-from=bounce+bd464f.74ae96-joe=example.com@s.backerkit.com; helo=mail-m86.mailgun.info;"
                        },
                        {
                            "name": "Authentication-Results",
                            "value": "amazonses.com; spf=pass (spfCheck: domain of s.backerkit.com designates 146.20.113.86 as permitted sender) client-ip=146.20.113.86; envelope-from=bounce+bd464f.74ae96-joe=example.com@s.backerkit.com; helo=mail-m86.mailgun.info; dkim=pass header.i=@s.backerkit.com; dmarc=pass header.from=s.backerkit.com;"
                        },
                        {
                            "name": "X-SES-RECEIPT",
                            "value": "AEFBQUFBQUFBQUFHa2FWZEVSVU9FeTl2WlRNQithZ0FVY1ZTc1A0eXBTaDh6VWZUNXJLL2t1YXo3OVQ2NWZ5S1c4RXZpSnRzTXpVRk9FZXZiNE4vL0ZYUmN4NjZMS3hNOVAvMHB2b2NsRjV5SWd5SUFtWXMzSHRHTVhPdmtPU0dLbkFJRWxWdHZkNGFkZ3c0ZjF4bkM4cTlSaEhwdUQ3UmR2YVdobnVyNGM4Z05WQUFzL3grSUl5ajFrY1U1c3hYVitPbUFaZTR4RWoxbDc4eFBYZHl0K29IOGg4WU04WEdIa0YvL1RYZVdWaU41NWo5SkJYcThPeDQ4WnRHb0dnSVpreVErUEFGSmdCYmZsdm9YZDdoVW5BcmtTd0preHNzWlhyVzFLMUtlUWFEQ1dCRnlYZy93OEtKNXJaVEpCSzdDZkZYMmxyK2dqYmtoaDh1WW5NVk1lSjl2YUp2ZHc4aEk="
                        },
                        {
                            "name": "X-SES-DKIM-SIGNATURE",
                            "value": "a=rsa-sha256; q=dns/txt; b=QKzHouII910NiOdeH22cApgP729DzBu5bFL1vDGEa8IPWf4GxbUzjf8a1KFsYHOO0Jeu5SqtXRe+x1ez3Kos5cTrZ2tOOOdEZkuSSiE1R3vJeS9p3dIGgwsLDFDwgmajKu9eMLG/gCxe9fPRpJ7KS9ZXma+Tz6Jr/3jsyOBG3JM=; c=relaxed/simple; s=224i4yxa5dv7c2xz3womw6peuasteono; d=amazonses.com; t=1585262402; v=1; bh=FNwI+y3+dBEnP/RZaeoitTtVb/dXvjR/Yt5HQURhPiU=; h=From:To:Cc:Bcc:Subject:Date:Message-ID:MIME-Version:Content-Type:X-SES-RECEIPT;"
                        },
                        {
                            "name": "DKIM-Signature",
                            "value": "a=rsa-sha256; v=1; c=relaxed/relaxed; d=s.backerkit.com; q=dns/txt; s=k1; t=1585262401; h=Content-Type:Mime-Version:Subject:From:To:Date:Message-Id:Mime-Version:Sender; bh=w9aUK0uetkkmwzcbvBhz4uTbqL+frO21EDgSaM5DryU=; b=rNfUL7x6mpkOVinquBVrjcesI6t83/xHO5bXvJ7Gg8kDU4hxdENB5JUzya3dGWaUUPBzYqIxgbB0Q60/mZdIwWckUQVzwifsATS/0W+PtMGP5/OtP0SFx+52IT/QlVVlC+r+fzs5xrSbqILYkZS6E6B2lmNgrUJKZbxjUhnTWys="
                        },
                        {
                            "name": "X-Mailgun-Sending-Ip",
                            "value": "146.20.113.86"
                        },
                        {
                            "name": "X-Mailgun-Sid",
                            "value": "WyIzZDQ5MyIsICJqb2VAcGhhdGpvZS5jb20iLCAiNzRhZTk2Il0="
                        },
                        {
                            "name": "Received",
                            "value": "by luna.mailgun.net with HTTP; Thu, 26 Mar 2020 22:39:51 +0000"
                        },
                        {
                            "name": "Sender",
                            "value": "no-reply@s.backerkit.com"
                        },
                        {
                            "name": "Mime-Version",
                            "value": "1.0"
                        },
                        {
                            "name": "Message-Id",
                            "value": "<5e7d2f3714d9b_383fdac17199dc9672f@b7c74396-34ca-44cf-a81e-37c001ce1572.mail>"
                        },
                        {
                            "name": "X-Mailgun-Tag",
                            "value": "{\"backer_id\":16588730,\"project_id\":19855}"
                        },
                        {
                            "name": "X-Mailgun-Variables",
                            "value": "{\"backer_id\":16588730,\"project_id\":19855,\"subject\":\"Response Needed -- Get your reward for Crimes in History: H. H. Holmes' Murder Castle\"}"
                        },
                        {
                            "name": "Date",
                            "value": "Thu, 26 Mar 2020 22:39:51 +0000"
                        },
                        {
                            "name": "To",
                            "value": "joe@example.com"
                        },
                        {
                            "name": "From",
                            "value": "\"Seth & Brandt @ Blueprint Gaming Concepts\" <no-reply@s.backerkit.com>"
                        },
                        {
                            "name": "Subject",
                            "value": "Response Needed -- Get your reward for Crimes in History: H. H. Holmes' Murder Castle"
                        },
                        {
                            "name": "Mime-Version",
                            "value": "1.0"
                        },
                        {
                            "name": "Content-Type",
                            "value": "multipart/alternative; boundary=\"b717a809412543e8ba52398ab24d42de\""
                        }
                    ],
                    "commonHeaders": {
                        "returnPath": "bounce+bd464f.74ae96-joe=example.com@s.backerkit.com",
                        "from": [
                            "\"Seth & Brandt @ Blueprint Gaming Concepts\" <no-reply@s.backerkit.com>"
                        ],
                        "sender": "no-reply@s.backerkit.com",
                        "date": "Thu, 26 Mar 2020 22:39:51 +0000",
                        "to": [
                            "joe@example.com"
                        ],
                        "messageId": "<5e7d2f3714d9b_383fdac17199dc9672f@b7c74396-34ca-44cf-a81e-37c001ce1572.mail>",
                        "subject": "Response Needed -- Get your reward for Crimes in History: H. H. Holmes' Murder Castle"
                    }
                },
                "receipt": {
                    "timestamp": "2020-03-26T22:39:58.712Z",
                    "processingTimeMillis": 165048,
                    "recipients": [
                        "joe@example.com"
                    ],
                    "spamVerdict": {
                        "status": "PASS"
                    },
                    "virusVerdict": {
                        "status": "PASS"
                    },
                    "spfVerdict": {
                        "status": "PASS"
                    },
                    "dkimVerdict": {
                        "status": "PASS"
                    },
                    "dmarcVerdict": {
                        "status": "PASS"
                    },
                    "action": {
                        "type": "Lambda",
                        "functionArn": "xxx",
                        "invocationType": "RequestResponse"
                    }
                }
            }
        }
    ]
}
```

The S3 object is also attached: [7agm2c84tgclj4ejvdvrjol7dq7s4l4v0ev2o4g1](https://github.com/lafiosca/reba/files/4841316/message.txt)

The SES send of the forwarded item yielded this error:
```
2020-03-26T22:42:44.038Z	40e5851c-a3e0-457d-9273-01621f8de0e8	{ InvalidParameterValue: Duplicate header 'MIME-Version'.
    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/query.js:47:29)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
  message: 'Duplicate header \'MIME-Version\'.',
  code: 'InvalidParameterValue',
  time: 2020-03-26T22:42:44.037Z,
  requestId: '9804008d-cecc-4544-aeee-14b37b95b6f6',
  statusCode: 400,
  retryable: false,
  retryDelay: 86.46501909116166 }
```

I don't want to have to try to dedupe/cleanup messages that are coming from external sources, but I do want to receive my email.

Suggested steps:
1. Refresh my mind on the header/body parsing/forwarding logic
2. See if we can do some kind of simple de-duping of Mime-Version at a minimum
3. Let's add in a new feature where we send an email to a specific address (a la postmaster) when these failures occur.

**Comment by lafiosca** [comment]
New logic de-dupes every header except `Received`
